# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mael Jullien
title: PhD Student
email: mael.jullien@postgrad.manchester.ac.uk

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: Mael_Jullien
github_username:  Mael7307
linkedin_username: maeljullien373
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
orcid_username: 0000-0002-0303-2046

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I am a Ph.D. student in the Department of Computer Science at the University of Manchester, as part of the 
  [Neuro-Symbolic AI Group](https://www.idiap.ch/en/scientific-research/neuro-symbolic-ai).
  
  My research focuses on investigating AI models, such as Large Language Models (LLMs), 
  to perform Natural Language Inference in the clinical domain, including tasks like 
  retrieving and ranking clinical trials for patients and classifying clinical trial protocol deviations. A key aspect of my work is designing hybrid neuro-symbolic architectures that are both explainable, and 
  integrated with ground knowledge, such as ontologies, for improved robustness, efficiency, and controllability. 
  Additionally, working to uncover inference mechanisms and limitations of LLMs.
  
content:

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: "[SemEval-2024 Task 2: Safe Biomedical Natural Language Inference for Clinical Trials](https://aclanthology.org/2024.semeval-1.271/)"
        caption: "SemEval, 2024"
        sub_title: "Co-authors: Mael Jullien, Marco Valentino, André Freitas"
        
      - layout: top
        title: "SemEval-2024 Task 2: Safe Biomedical Natural Language Inference for Clinical Trials"
        caption: "SemEval, 2024"
        sub_title: "Co-authors: Mael Jullien, Marco Valentino, André Freitas"
        link: "https://aclanthology.org/2024.semeval-1.271/"
        
      - layout: top
        title: "SemEval-2024 Task 2: Safe Biomedical Natural Language Inference for Clinical Trials"
        caption: "SemEval, 2024"
        sub_title: "Co-authors: Mael Jullien, Marco Valentino, André Freitas"
        link: "https://aclanthology.org/2024.semeval-1.271/"
        
      - layout: top
        title: "SemEval-2024 Task 2: Safe Biomedical Natural Language Inference for Clinical Trials"
        caption: "SemEval, 2024"
        sub_title: "Co-authors: Mael Jullien, Marco Valentino, André Freitas"
        link: "https://aclanthology.org/2024.semeval-1.271/"

      - layout: top
        title: "SemEval-2024 Task 2: Safe Biomedical Natural Language Inference for Clinical Trials"
        caption: "SemEval, 2024"
        sub_title: "Co-authors: Mael Jullien, Marco Valentino, André Freitas"
        link: "https://aclanthology.org/2024.semeval-1.271/"
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Nottingham
        caption: 2020
        sub_title: MSc in Computer Science and Artificial Intelligence (Distinction)
        quote: >
          Thesis: "Histological Image Registration using Deep Convolutional Features"
        description: | # this will include new lines to allow paragraphs
          During my MSc, I developed a strong foundation in Artificial Intelligence, focusing on key areas such as convolutional neural networks. My dissertation work centered on applying AI to the clinical domain, which has been pivotal in shaping my research direction.

      - layout: left
        title: University of Leicester
        caption: 2019
        sub_title: BSc Hons in Mathematics (First Class Honours)
        quote: >
          Thesis: "Convolutional Neural Networks for Audio Classification" 
        description: | # this will include new lines to allow paragraphs
          During my BSc, I honed my mathematical reasoning and problem-solving skills, which laid the groundwork for my transition into AI and computational research. My studies included a deep dive into algebra, calculus, and statistics, which have proven essential in my current research.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
